// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DbConnection;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MfgDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int");

                    b.Property<string>("ProductSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MfgDate = new DateTime(2023, 11, 2, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9019),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 2,
                            MfgDate = new DateTime(2023, 11, 1, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9059),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            MfgDate = new DateTime(2023, 10, 31, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9062),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 4,
                            MfgDate = new DateTime(2023, 10, 30, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9065),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 5,
                            MfgDate = new DateTime(2023, 10, 29, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9067),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 6,
                            MfgDate = new DateTime(2023, 10, 28, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9071),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 7,
                            MfgDate = new DateTime(2023, 10, 27, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9073),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 8,
                            MfgDate = new DateTime(2023, 10, 26, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9075),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            MfgDate = new DateTime(2023, 10, 25, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9077),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 10,
                            MfgDate = new DateTime(2023, 10, 24, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9081),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 11,
                            MfgDate = new DateTime(2023, 10, 23, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9083),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 12,
                            MfgDate = new DateTime(2023, 10, 22, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9085),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 13,
                            MfgDate = new DateTime(2023, 10, 21, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9087),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 14,
                            MfgDate = new DateTime(2023, 10, 20, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9089),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 15,
                            MfgDate = new DateTime(2023, 10, 19, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9091),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 16,
                            MfgDate = new DateTime(2023, 10, 18, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9093),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 17,
                            MfgDate = new DateTime(2023, 10, 17, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9095),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        },
                        new
                        {
                            Id = 18,
                            MfgDate = new DateTime(2023, 10, 16, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9099),
                            ProductCategory = "Economy",
                            ProductName = "Small",
                            ProductPrice = 275,
                            ProductSize = "Small"
                        },
                        new
                        {
                            Id = 19,
                            MfgDate = new DateTime(2023, 10, 15, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9101),
                            ProductCategory = "Standard",
                            ProductName = "Large",
                            ProductPrice = 100,
                            ProductSize = "Large"
                        },
                        new
                        {
                            Id = 20,
                            MfgDate = new DateTime(2023, 10, 14, 20, 16, 28, 878, DateTimeKind.Local).AddTicks(9103),
                            ProductCategory = "Premium",
                            ProductName = "Medium",
                            ProductPrice = 500,
                            ProductSize = "Medium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
